Transform: AWS::Serverless-2016-10-31
Resources:
  stdreamReader:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName: !Ref 'table'
            StreamName: '*'

      Events:
        tableEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt [ table, StreamArn ]
            StartingPosition: TRIM_HORIZON
            BatchSize: 25

  table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: offset
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        -
          AttributeName: offset
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  tableName:
    Value: !Ref 'table'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'table' ]]
