Transform: AWS::Serverless-2016-10-31
Resources:
  writeToTable:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue 'stdream-reader-test:table'

      Environment:
        Variables:
          TABLE_NAME: !ImportValue 'stdream-reader-test:table'
      Events:
       EveryFiveMinAt0:
         Type: Schedule
         Properties:
           Schedule: cron(0,5,10,15,20,25,30,35,40,45,50,55 * * * ? *)
       EveryFiveMinAt1:
         Type: Schedule
         Properties:
           Schedule: cron(1,6,11,16,21,26,31,36,41,46,51,56 * * * ? *)
       EveryFiveMinAt2:
         Type: Schedule
         Properties:
           Schedule: cron(2,7,12,17,22,27,32,37,42,47,52,57 * * * ? *)
       EveryFiveMinAt3:
         Type: Schedule
         Properties:
           Schedule: cron(3,8,13,18,23,28,33,38,43,48,53,58 * * * ? *)
       EveryFiveMinAt4:
         Type: Schedule
         Properties:
           Schedule: cron(4,9,14,19,24,29,34,39,44,49,54,59 * * * ? *)
