Transform: AWS::Serverless-2016-10-31
Resources:
  writeToTable:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue 'stdream-reader-test:table'

      Environment:
        Variables:
          TABLE_NAME: !ImportValue 'stdream-reader-test:table'
      Events:
       EveryFiveMinutesAt1:
         Type: Schedule
         Properties:
           Schedule: cron(1,6,11,16,21,26,31,36,41,46,51,56 * * * ? *)