Transform: AWS::Serverless-2016-10-31
Resources:
  writeEverySixMinutes:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "cron(0/6 * * * ? *)"
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - writeToTable
              - Arn
          Id: Write-v1

  PermissionForEventToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: writeToTable
      Action: lambda:InvokeFunction
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - writeEverySixMinutes
          - Arn

  writeToTable:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue 'stdream-reader-test:table'

      Environment:
        Variables:
          TABLE_NAME: !ImportValue 'stdream-reader-test:table'
